name: CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-22.04"
    steps:
      - name: zapier app 
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 120
      - run: |
            ${{ steps.setup-chrome.outputs.chrome-path }} --version
        
