name: CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-22.04"
    if: github.ref_name == 'main' || contains(github.event.head_commit.message, '[deploy-zap]')
    steps:
      - name: zapier app 
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 120
      - run: echo hoge
        
