# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: "ubuntu-22.04"
    steps:
      - name: zapier app version bump
        if: github.ref == 'refs/heads/master'
        uses: phips28/gh-action-bump-version@v9.1.0
        with:
          major-wording: '[bump-zap major]'
          minor-wording: '[bump-zap minor]'
          patch-wording: ${{ null }}
          rc-wording: ${{ null }}
          default: "patch"
          bump-policy: "ignore"
          skip-tag: "true"
          skip-push: "true"
          commit-message: "chore(zapier): bumped to v{{version}}"
