name: CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-22.04"
    steps:
      - uses: browser-actions/setup-chrome@v1
      - run: chrome --version
        
