name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-22.04"
    if: github.ref_name == 'main' || contains(github.event.head_commit.message, '[deploy-zap]')
    steps:
      - name: zapier app 
        run: echo hoge
        
